name: builder
version: 0.1.0.0
github: "codgician/codgician.github.io"
license: MIT
author: "codgician"
maintainer: "codgician"
copyright: "2025 codgician"
extra-source-files:
  - README.md
  - CHANGELOG.md
description: Static site generator for codgician.me
dependencies:
  - base >= 4.7 && < 5
  - hakyll >= 4.16
  - pandoc >= 3.0
  - pandoc-types >= 1.23
  - text
  - bytestring
  - filepath
  - directory
  - process
  - yaml
  - aeson
  - time
  - containers
  - cryptohash-sha256
  - base16-bytestring
  - temporary

ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-deriving-strategies
  - -Wunused-packages
  - -Wunused-type-patterns
  - -Wduplicate-exports
  - -Wprepositive-qualified-module

library:
  source-dirs: src
  exposed-modules:
    - Compiler.Cache
    - Compiler.KaTeX
    - Compiler.Mermaid
    - Compiler.Pandoc
    - Config
    - Context
    - Feed
    - Paginate
    - Site

executables:
  site:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - builder

tests:
  builder-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - builder
      - hspec
      - containers
