on-unmatched = "debug"

[formatter.haskell]
command = "ormolu"
includes = ["*.hs"]

[formatter.nix]
command = "nixfmt"
options = []
includes = [ "*.nix" ]
excludes = []

[formatter.yaml]
command = "yamlfmt"
includes = [ "*.yaml", "*.yml" ]

[formatter.markdown]
command = "prettier"
options = ["--prose-wrap", "always", "--print-width", "80", "--write"]
includes = ["*.md"]