# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  lucide-static = {
    pname = "lucide-static";
    version = "1.8.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/lucide-static/-/lucide-static-1.8.0.tgz";
      sha256 = "sha256-3SMidHnvtbL2mS2UdP5bfkfyjf3XeKFpWPB9Q8iFAJk=";
    };
  };
  reveal-js = {
    pname = "reveal-js";
    version = "6.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/reveal.js/-/reveal.js-6.0.1.tgz";
      sha256 = "sha256-ejvFCWxDW4k/10iP9ETBwcIy4eaYe23mhpbnBkN9Ck8=";
    };
  };
}
