# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  reveal-js = {
    pname = "reveal-js";
    version = "6.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/reveal.js/-/reveal.js-6.0.1.tgz";
      sha256 = "sha256-ejvFCWxDW4k/10iP9ETBwcIy4eaYe23mhpbnBkN9Ck8=";
    };
  };
  tabler-icons-webfont = {
    pname = "tabler-icons-webfont";
    version = "3.44.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@tabler/icons-webfont/-/icons-webfont-3.44.0.tgz";
      sha256 = "sha256-BF0YahFpEk1tBXH38s+s7YWbNqCBHobH4YHR8tT0MbI=";
    };
  };
}
