# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  reveal-js = {
    pname = "reveal-js";
    version = "6.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/reveal.js/-/reveal.js-6.0.2.tgz";
      sha256 = "sha256-Lwwgv7AkR6GYoevoqMCXpUN9A1yqOPKCC/S6iHo+rJE=";
    };
  };
  tabler-icons-webfont = {
    pname = "tabler-icons-webfont";
    version = "3.46.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@tabler/icons-webfont/-/icons-webfont-3.46.0.tgz";
      sha256 = "sha256-lmTNT9uuOiWlI9nk0qkistlGBJUELmjxCHpV1jVArvQ=";
    };
  };
}
